[package]
name = "tar_light"
version = "0.1.0"
edition = "2024"
authors = ["kujirahand"]
description = "Simple tar archive reader and writer library"
license = "MIT"
repository = "https://github.com/kujirahand/rust-tar_light"
readme = "README.md"
keywords = ["tar", "archive"]
categories = ["filesystem"]

[dependencies]
